name: Publish

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Publish `parenv-derive`
      run: cargo publish -p parenv-derive

    - name: Publish `parenv`
      run: cargo publish -p parenv
